export const routesData = [
  {id: '0',
    name: "The Five Lakes Trail to Fernsteinsee",
    activity: "trailrunning",
    difficulty: "moderate",
    length: "10 km",
    altitude: "1307 hm",
  },
  {id: '1',
    name: "Kranzhorn",
    activity: "hiking",
    difficulty: "easy",
    length: "9.2 km",
    altitude: "888 hm",
  },
  {id: '2',
    name: "Jubiläumsgrat",
    activity: "climbing",
    difficulty: "difficult",
    length: "24.9 km",
    altitude: "2299 hm",
  },
  {id: '3',
    name: "Großglockner Normalweg",
    activity: "hiking",
    difficulty: "difficult",
    length: "8 km",
    altitude: "1737 hm",
  },
];

